name: Ejecucion Generador de Data

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: ☕️ Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Ejecutar tests con Maven
        run: mvn clean test

      - name: Compilar el proyecto
        run: mvn package

      - name: Ejecutar generador de usuarios
        run: java -cp target/classes com.latam.App 10

      - name: Subir users.csv como artifact
        uses: actions/upload-artifact@v4
        with:
          name: users-csv
          path: users.csv
